version: "3"
volumes:
  postgres-data:
    driver: local
services:
  db:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: rajput
      POSTGRES_USER: ankit
    volumes:
      - postgres-data:/var/lib/postgresql/postdata
  springbootwebflux:
    build:
      context: ./Spring_boot_2_webflux
    command: mvn clean spring-boot:run
    restart: always
    ports:
      - "8090:8090"
    depends_on:
      - db
  springbootwebclient:
    build:
      context: ./Spring_boot_2_webclient
    restart: always
    ports:
      - "8080:8080"
    links:
      - springbootwebflux
    depends_on:
      - springbootwebflux
